### ISSUE TITLE
Is it production-ready?

### ISSUE THREAD

**Issue by piotr-yuxuan** [gnarroway/fumi#2]
Hello,

This project looks nice. Is it production-ready? Have you ever had some real-life use cases for it? :-)

Thanks,

Piotr

**Comment by gnarroway** [comment]
Thanks for your interest :)

We use it in all our Clojure services in production scraped by Prometheus together with grafana and alertmanager. The public documented api is stable but the internals may change in the future. 

Do try it out and let me know if it works for you!

**Comment by piotr-yuxuan** [comment]
Most awesome

**Comment by piotr-yuxuan** [comment]
Just to gather some more feedback, what has been your biggest issue so far with this library?

**Comment by gnarroway** [comment]
There has not really been issues. It does what it says on the box. 

That said, from an ease of use perspective, we originally used custom registries passed through context maps (since we use integrant/component style architecture). However, most of the time we found it is nicer to just use the default registry. It makes it easier to test your business logic without unnecessarily mocking things that are orthogonal to it (ie the metrics). 

Also we are not a business that processes millions of events a second so I can’t comment on usability at that scale.

**Comment by piotr-yuxuan** [comment]
I'll let you know once we reach that scale, if ever ;-)
